### ISSUE TITLE
Bug: Change copyright statement to 2023

### ISSUE THREAD

**Issue by oliwolff1** [kinde-starter-kits/javascript-starter-kit#2]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Change copyright statement on starter kit to the following: © 2023 KindeAuth, Inc. All rights reserved

### Starter kit URL

https://github.com/kinde-starter-kits/javascript-starter-kit

### Operating system(s)

macOS

### Operating system version(s)

macOS Ventura 13.4.1

**Comment by DaveOrDead** [comment]
Fixed by #3
