### ISSUE TITLE
renderLoggedInView is always called twice after successful login

### ISSUE THREAD

**Issue by paulfalgout** [kinde-starter-kits/javascript-starter-kit#5]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Upon successful login `renderLoggedInView` is called inside the redirect handler, but then it's also called in the default `render`

### Starter kit URL

https://github.com/kinde-starter-kits/javascript-starter-kit

### Operating system(s)

macOS

### Operating system version(s)

n/a

### Additional information

Perhaps this is not an issue for this lib, but going from this as a model immediately had me duplicating initial API calls.

**Comment by DaveOrDead** [comment]
Thanks for flagging this @paulfalgout this should now be fixed
